# Semana 2 - Aula 2

# Loop

In [2]:
fila = ["Alice", "Bob", "Charlie"]

for nome in fila:
        print(nome)

Alice
Bob
Charlie

# Dados fictícios

In [20]:
import random

def generate_cpf():
    """Generates a plausible alphanumeric CPF (e.g., XXX.YYY.ZZZ-DD)."""
    # Generate 9 random digits for the main part
    digits = ''.join([str(random.randint(0, 9)) for _ in range(9)])

    # Calculate the first verifier digit
    sum_val = 0
    for i in range(9):
        sum_val += int(digits[i]) * (10 - i)
    v1 = (sum_val * 10) % 11
    if v1 == 10:
        v1 = 0

    # Append first verifier digit
    digits += str(v1)

    # Calculate the second verifier digit
    sum_val = 0
    for i in range(10):
        sum_val += int(digits[i]) * (11 - i)
    v2 = (sum_val * 10) % 11
    if v2 == 10:
        v2 = 0

    # Append second verifier digit
    digits += str(v2)

    # Format as XXX.YYY.ZZZ-DD
    return f"{digits[0:3]}.{digits[3:6]}.{digits[6:9]}-{digits[9:11]}"


first_names = [
    "Ana", "Bruno", "Carla", "Daniel", "Eduarda", "Felipe", "Gabriela",
    "Henrique", "Isabela", "João", "Larissa", "Marcelo", "Natalia", "Otavio",
    "Patricia", "Rafael", "Sabrina", "Thiago", "Ursula", "Victor"
]

last_names = [
    "Silva", "Santos", "Oliveira", "Souza", "Lima", "Pereira", "Ferreira",
    "Almeida", "Costa", "Rodrigues", "Martins", "Carvalho", "Ribeiro", "Gomes",
    "Dias", "Fernandes", "Gonçalves", "Mendes", "Nunes", "Rocha"
]

random.seed(1)
clientes = []

for _ in range(20):
    nome = random.choice(first_names)
    sobrenome = random.choice(last_names)
    # Ensure unique CPF for each customer, though unlikely to collide in small sample
    cpf = generate_cpf()
    renda = round(random.uniform(2000, 15000), 2)  # Renda entre 2000 e 15000
    score_credito = random.randint(300, 900)  # Score de crédito entre 300 e 900

    cliente = {
        "cpf": cpf,
        "nome": nome,
        "sobrenome": sobrenome,
        "renda": renda,
        "score_credito": score_credito
    }
    clientes.append(cliente)

# Display the generated list of clients
for cliente in clientes:
    print(cliente)

{'cpf': '141.777.631-52', 'nome': 'Eduarda', 'sobrenome': 'Nunes', 'renda': 8342.14, 'score_credito': 699}
{'cpf': '074.391.500-31', 'nome': 'Otavio', 'sobrenome': 'Rocha', 'renda': 2330.8, 'score_credito': 854}
{'cpf': '360.837.783-28', 'nome': 'Ana', 'sobrenome': 'Ribeiro', 'renda': 6494.11, 'score_credito': 524}
{'cpf': '068.124.158-63', 'nome': 'Patricia', 'sobrenome': 'Rodrigues', 'renda': 14173.73, 'score_credito': 732}
{'cpf': '449.786.907-57', 'nome': 'Sabrina', 'sobrenome': 'Ferreira', 'renda': 5155.62, 'score_credito': 713}
{'cpf': '585.178.128-91', 'nome': 'Otavio', 'sobrenome': 'Pereira', 'renda': 12919.37, 'score_credito': 679}
{'cpf': '704.999.622-06', 'nome': 'Rafael', 'sobrenome': 'Silva', 'renda': 8529.1, 'score_credito': 312}
{'cpf': '836.859.574-65', 'nome': 'Gabriela', 'sobrenome': 'Mendes', 'renda': 10569.79, 'score_credito': 305}
{'cpf': '288.360.759-16', 'nome': 'Natalia', 'sobrenome': 'Gonçalves', 'renda': 9207.22, 'score_credito': 816}
{'cpf': '565.088.995-38', 'nome': 'Otavio', 'sobrenome': 'Fernandes', 'renda': 7955.91, 'score_credito': 328}
{'cpf': '892.184.011-73', 'nome': 'Henrique', 'sobrenome': 'Pereira', 'renda': 13285.02, 'score_credito': 763}
{'cpf': '341.925.412-11', 'nome': 'Ana', 'sobrenome': 'Costa', 'renda': 4075.13, 'score_credito': 840}
{'cpf': '475.771.046-12', 'nome': 'Felipe', 'sobrenome': 'Costa', 'renda': 6463.45, 'score_credito': 492}
{'cpf': '483.960.306-50', 'nome': 'Isabela', 'sobrenome': 'Souza', 'renda': 3904.0, 'score_credito': 464}
{'cpf': '683.873.806-60', 'nome': 'Patricia', 'sobrenome': 'Gonçalves', 'renda': 10773.73, 'score_credito': 628}
{'cpf': '423.041.144-82', 'nome': 'Otavio', 'sobrenome': 'Santos', 'renda': 11669.95, 'score_credito': 726}
{'cpf': '208.093.972-69', 'nome': 'Ursula', 'sobrenome': 'Costa', 'renda': 12762.87, 'score_credito': 821}
{'cpf': '351.396.937-63', 'nome': 'Bruno', 'sobrenome': 'Ribeiro', 'renda': 3357.51, 'score_credito': 699}
{'cpf': '705.964.023-17', 'nome': 'João', 'sobrenome': 'Gonçalves', 'renda': 13147.98, 'score_credito': 876}
{'cpf': '634.168.587-43', 'nome': 'Eduarda', 'sobrenome': 'Martins', 'renda': 11983.37, 'score_credito': 845}

### Print como array

In [21]:
print(clientes)

[{'cpf': '141.777.631-52', 'nome': 'Eduarda', 'sobrenome': 'Nunes', 'renda': 8342.14, 'score_credito': 699}, {'cpf': '074.391.500-31', 'nome': 'Otavio', 'sobrenome': 'Rocha', 'renda': 2330.8, 'score_credito': 854}, {'cpf': '360.837.783-28', 'nome': 'Ana', 'sobrenome': 'Ribeiro', 'renda': 6494.11, 'score_credito': 524}, {'cpf': '068.124.158-63', 'nome': 'Patricia', 'sobrenome': 'Rodrigues', 'renda': 14173.73, 'score_credito': 732}, {'cpf': '449.786.907-57', 'nome': 'Sabrina', 'sobrenome': 'Ferreira', 'renda': 5155.62, 'score_credito': 713}, {'cpf': '585.178.128-91', 'nome': 'Otavio', 'sobrenome': 'Pereira', 'renda': 12919.37, 'score_credito': 679}, {'cpf': '704.999.622-06', 'nome': 'Rafael', 'sobrenome': 'Silva', 'renda': 8529.1, 'score_credito': 312}, {'cpf': '836.859.574-65', 'nome': 'Gabriela', 'sobrenome': 'Mendes', 'renda': 10569.79, 'score_credito': 305}, {'cpf': '288.360.759-16', 'nome': 'Natalia', 'sobrenome': 'Gonçalves', 'renda': 9207.22, 'score_credito': 816}, {'cpf': '565.088.995-38', 'nome': 'Otavio', 'sobrenome': 'Fernandes', 'renda': 7955.91, 'score_credito': 328}, {'cpf': '892.184.011-73', 'nome': 'Henrique', 'sobrenome': 'Pereira', 'renda': 13285.02, 'score_credito': 763}, {'cpf': '341.925.412-11', 'nome': 'Ana', 'sobrenome': 'Costa', 'renda': 4075.13, 'score_credito': 840}, {'cpf': '475.771.046-12', 'nome': 'Felipe', 'sobrenome': 'Costa', 'renda': 6463.45, 'score_credito': 492}, {'cpf': '483.960.306-50', 'nome': 'Isabela', 'sobrenome': 'Souza', 'renda': 3904.0, 'score_credito': 464}, {'cpf': '683.873.806-60', 'nome': 'Patricia', 'sobrenome': 'Gonçalves', 'renda': 10773.73, 'score_credito': 628}, {'cpf': '423.041.144-82', 'nome': 'Otavio', 'sobrenome': 'Santos', 'renda': 11669.95, 'score_credito': 726}, {'cpf': '208.093.972-69', 'nome': 'Ursula', 'sobrenome': 'Costa', 'renda': 12762.87, 'score_credito': 821}, {'cpf': '351.396.937-63', 'nome': 'Bruno', 'sobrenome': 'Ribeiro', 'renda': 3357.51, 'score_credito': 699}, {'cpf': '705.964.023-17', 'nome': 'João', 'sobrenome': 'Gonçalves', 'renda': 13147.98, 'score_credito': 876}, {'cpf': '634.168.587-43', 'nome': 'Eduarda', 'sobrenome': 'Martins', 'renda': 11983.37, 'score_credito': 845}]

In [22]:
display(clientes)

[{'cpf': '141.777.631-52',
  'nome': 'Eduarda',
  'sobrenome': 'Nunes',
  'renda': 8342.14,
  'score_credito': 699},
 {'cpf': '074.391.500-31',
  'nome': 'Otavio',
  'sobrenome': 'Rocha',
  'renda': 2330.8,
  'score_credito': 854},
 {'cpf': '360.837.783-28',
  'nome': 'Ana',
  'sobrenome': 'Ribeiro',
  'renda': 6494.11,
  'score_credito': 524},
 {'cpf': '068.124.158-63',
  'nome': 'Patricia',
  'sobrenome': 'Rodrigues',
  'renda': 14173.73,
  'score_credito': 732},
 {'cpf': '449.786.907-57',
  'nome': 'Sabrina',
  'sobrenome': 'Ferreira',
  'renda': 5155.62,
  'score_credito': 713},
 {'cpf': '585.178.128-91',
  'nome': 'Otavio',
  'sobrenome': 'Pereira',
  'renda': 12919.37,
  'score_credito': 679},
 {'cpf': '704.999.622-06',
  'nome': 'Rafael',
  'sobrenome': 'Silva',
  'renda': 8529.1,
  'score_credito': 312},
 {'cpf': '836.859.574-65',
  'nome': 'Gabriela',
  'sobrenome': 'Mendes',
  'renda': 10569.79,
  'score_credito': 305},
 {'cpf': '288.360.759-16',
  'nome': 'Natalia',
  'sobrenome': 'Gonçalves',
  'renda': 9207.22,
  'score_credito': 816},
 {'cpf': '565.088.995-38',
  'nome': 'Otavio',
  'sobrenome': 'Fernandes',
  'renda': 7955.91,
  'score_credito': 328},
 {'cpf': '892.184.011-73',
  'nome': 'Henrique',
  'sobrenome': 'Pereira',
  'renda': 13285.02,
  'score_credito': 763},
 {'cpf': '341.925.412-11',
  'nome': 'Ana',
  'sobrenome': 'Costa',
  'renda': 4075.13,
  'score_credito': 840},
 {'cpf': '475.771.046-12',
  'nome': 'Felipe',
  'sobrenome': 'Costa',
  'renda': 6463.45,
  'score_credito': 492},
 {'cpf': '483.960.306-50',
  'nome': 'Isabela',
  'sobrenome': 'Souza',
  'renda': 3904.0,
  'score_credito': 464},
 {'cpf': '683.873.806-60',
  'nome': 'Patricia',
  'sobrenome': 'Gonçalves',
  'renda': 10773.73,
  'score_credito': 628},
 {'cpf': '423.041.144-82',
  'nome': 'Otavio',
  'sobrenome': 'Santos',
  'renda': 11669.95,
  'score_credito': 726},
 {'cpf': '208.093.972-69',
  'nome': 'Ursula',
  'sobrenome': 'Costa',
  'renda': 12762.87,
  'score_credito': 821},
 {'cpf': '351.396.937-63',
  'nome': 'Bruno',
  'sobrenome': 'Ribeiro',
  'renda': 3357.51,
  'score_credito': 699},
 {'cpf': '705.964.023-17',
  'nome': 'João',
  'sobrenome': 'Gonçalves',
  'renda': 13147.98,
  'score_credito': 876},
 {'cpf': '634.168.587-43',
  'nome': 'Eduarda',
  'sobrenome': 'Martins',
  'renda': 11983.37,
  'score_credito': 845}]

### Print lista arrumada

print(f"")
Variáveis chamadas em {}, lista['campo_da_lista']

In [23]:
print("Lista de clientes:\n")
for cliente in clientes:
    print(f"CPF: {cliente['cpf']} \nNome: {cliente['nome']} {cliente['sobrenome']} \nRenda: {cliente['renda']} \nScore de Crédito: {cliente['score_credito']} \n-----")

Lista de clientes:

CPF: 141.777.631-52
Nome: Eduarda Nunes
Renda: 8342.14
Score de Crédito: 699
-----
CPF: 074.391.500-31
Nome: Otavio Rocha
Renda: 2330.8
Score de Crédito: 854
-----
CPF: 360.837.783-28
Nome: Ana Ribeiro
Renda: 6494.11
Score de Crédito: 524
-----
CPF: 068.124.158-63
Nome: Patricia Rodrigues
Renda: 14173.73
Score de Crédito: 732
-----
CPF: 449.786.907-57
Nome: Sabrina Ferreira
Renda: 5155.62
Score de Crédito: 713
-----
CPF: 585.178.128-91
Nome: Otavio Pereira
Renda: 12919.37
Score de Crédito: 679
-----
CPF: 704.999.622-06
Nome: Rafael Silva
Renda: 8529.1
Score de Crédito: 312
-----
CPF: 836.859.574-65
Nome: Gabriela Mendes
Renda: 10569.79
Score de Crédito: 305
-----
CPF: 288.360.759-16
Nome: Natalia Gonçalves
Renda: 9207.22
Score de Crédito: 816
-----
CPF: 565.088.995-38
Nome: Otavio Fernandes
Renda: 7955.91
Score de Crédito: 328
-----
CPF: 892.184.011-73
Nome: Henrique Pereira
Renda: 13285.02
Score de Crédito: 763
-----
CPF: 341.925.412-11
Nome: Ana Costa
Renda: 4075.13
Score de Crédito: 840
-----
CPF: 475.771.046-12
Nome: Felipe Costa
Renda: 6463.45
Score de Crédito: 492
-----
CPF: 483.960.306-50
Nome: Isabela Souza
Renda: 3904.0
Score de Crédito: 464
-----
CPF: 683.873.806-60
Nome: Patricia Gonçalves
Renda: 10773.73
Score de Crédito: 628
-----
CPF: 423.041.144-82
Nome: Otavio Santos
Renda: 11669.95
Score de Crédito: 726
-----
CPF: 208.093.972-69
Nome: Ursula Costa
Renda: 12762.87
Score de Crédito: 821
-----
CPF: 351.396.937-63
Nome: Bruno Ribeiro
Renda: 3357.51
Score de Crédito: 699
-----
CPF: 705.964.023-17
Nome: João Gonçalves
Renda: 13147.98
Score de Crédito: 876
-----
CPF: 634.168.587-43
Nome: Eduarda Martins
Renda: 11983.37
Score de Crédito: 845
-----

### Print como dataframe

In [24]:
import pandas as pd

df_clientes = pd.DataFrame(clientes)
print(df_clientes)

               cpf      nome  sobrenome     renda  score_credito
0   141.777.631-52   Eduarda      Nunes   8342.14            699
1   074.391.500-31    Otavio      Rocha   2330.80            854
2   360.837.783-28       Ana    Ribeiro   6494.11            524
3   068.124.158-63  Patricia  Rodrigues  14173.73            732
4   449.786.907-57   Sabrina   Ferreira   5155.62            713
5   585.178.128-91    Otavio    Pereira  12919.37            679
6   704.999.622-06    Rafael      Silva   8529.10            312
7   836.859.574-65  Gabriela     Mendes  10569.79            305
8   288.360.759-16   Natalia  Gonçalves   9207.22            816
9   565.088.995-38    Otavio  Fernandes   7955.91            328
10  892.184.011-73  Henrique    Pereira  13285.02            763
11  341.925.412-11       Ana      Costa   4075.13            840
12  475.771.046-12    Felipe      Costa   6463.45            492
13  483.960.306-50   Isabela      Souza   3904.00            464
14  683.873.806-60  Patricia  Gonçalves  10773.73            628
15  423.041.144-82    Otavio     Santos  11669.95            726
16  208.093.972-69    Ursula      Costa  12762.87            821
17  351.396.937-63     Bruno    Ribeiro   3357.51            699
18  705.964.023-17      João  Gonçalves  13147.98            876
19  634.168.587-43   Eduarda    Martins  11983.37            845

# For + if

In [33]:
for cliente in clientes:
  if cliente['score_credito'] >= 600:
    print(cliente['nome'], cliente['score_credito'], "- Aprovado ✅.")
  else:
    print(cliente['nome'], cliente['score_credito'], "- Reprovado automaticamente ❌. Em análise manual.")

Eduarda 699 - Aprovado ✅.
Otavio 854 - Aprovado ✅.
Ana 524 - Reprovado automaticamente ❌. Em análise manual.
Patricia 732 - Aprovado ✅.
Sabrina 713 - Aprovado ✅.
Otavio 679 - Aprovado ✅.
Rafael 312 - Reprovado automaticamente ❌. Em análise manual.
Gabriela 305 - Reprovado automaticamente ❌. Em análise manual.
Natalia 816 - Aprovado ✅.
Otavio 328 - Reprovado automaticamente ❌. Em análise manual.
Henrique 763 - Aprovado ✅.
Ana 840 - Aprovado ✅.
Felipe 492 - Reprovado automaticamente ❌. Em análise manual.
Isabela 464 - Reprovado automaticamente ❌. Em análise manual.
Patricia 628 - Aprovado ✅.
Otavio 726 - Aprovado ✅.
Ursula 821 - Aprovado ✅.
Bruno 699 - Aprovado ✅.
João 876 - Aprovado ✅.
Eduarda 845 - Aprovado ✅.

[{'cpf': '141.777.631-52',
  'nome': 'Eduarda',
  'sobrenome': 'Nunes',
  'renda': 8342.14,
  'score_credito': 699},
 {'cpf': '074.391.500-31',
  'nome': 'Otavio',
  'sobrenome': 'Rocha',
  'renda': 2330.8,
  'score_credito': 854},
 {'cpf': '360.837.783-28',
  'nome': 'Ana',
  'sobrenome': 'Ribeiro',
  'renda': 6494.11,
  'score_credito': 524},
 {'cpf': '068.124.158-63',
  'nome': 'Patricia',
  'sobrenome': 'Rodrigues',
  'renda': 14173.73,
  'score_credito': 732},
 {'cpf': '449.786.907-57',
  'nome': 'Sabrina',
  'sobrenome': 'Ferreira',
  'renda': 5155.62,
  'score_credito': 713},
 {'cpf': '585.178.128-91',
  'nome': 'Otavio',
  'sobrenome': 'Pereira',
  'renda': 12919.37,
  'score_credito': 679},
 {'cpf': '704.999.622-06',
  'nome': 'Rafael',
  'sobrenome': 'Silva',
  'renda': 8529.1,
  'score_credito': 312},
 {'cpf': '836.859.574-65',
  'nome': 'Gabriela',
  'sobrenome': 'Mendes',
  'renda': 10569.79,
  'score_credito': 305},
 {'cpf': '288.360.759-16',
  'nome': 'Natalia',
  'sobrenome': 'Gonçalves',
  'renda': 9207.22,
  'score_credito': 816},
 {'cpf': '565.088.995-38',
  'nome': 'Otavio',
  'sobrenome': 'Fernandes',
  'renda': 7955.91,
  'score_credito': 328},
 {'cpf': '892.184.011-73',
  'nome': 'Henrique',
  'sobrenome': 'Pereira',
  'renda': 13285.02,
  'score_credito': 763},
 {'cpf': '341.925.412-11',
  'nome': 'Ana',
  'sobrenome': 'Costa',
  'renda': 4075.13,
  'score_credito': 840},
 {'cpf': '475.771.046-12',
  'nome': 'Felipe',
  'sobrenome': 'Costa',
  'renda': 6463.45,
  'score_credito': 492},
 {'cpf': '483.960.306-50',
  'nome': 'Isabela',
  'sobrenome': 'Souza',
  'renda': 3904.0,
  'score_credito': 464},
 {'cpf': '683.873.806-60',
  'nome': 'Patricia',
  'sobrenome': 'Gonçalves',
  'renda': 10773.73,
  'score_credito': 628},
 {'cpf': '423.041.144-82',
  'nome': 'Otavio',
  'sobrenome': 'Santos',
  'renda': 11669.95,
  'score_credito': 726},
 {'cpf': '208.093.972-69',
  'nome': 'Ursula',
  'sobrenome': 'Costa',
  'renda': 12762.87,
  'score_credito': 821},
 {'cpf': '351.396.937-63',
  'nome': 'Bruno',
  'sobrenome': 'Ribeiro',
  'renda': 3357.51,
  'score_credito': 699},
 {'cpf': '705.964.023-17',
  'nome': 'João',
  'sobrenome': 'Gonçalves',
  'renda': 13147.98,
  'score_credito': 876},
 {'cpf': '634.168.587-43',
  'nome': 'Eduarda',
  'sobrenome': 'Martins',
  'renda': 11983.37,
  'score_credito': 845}]

# Classe

In [37]:
# Definição da classe Conta para representar uma conta bancária
class Conta:
    def __init__(self, titular, saldo):
        # Construtor da classe Conta
        # Inicializa a conta com um titular e um saldo inicial
        self.titular = titular
        self.saldo = saldo
        print(f"Conta criada para {self.titular} com saldo inicial de R$ {self.saldo:.2f}.")

    def depositar(self, valor):
        # Método para depositar um valor na conta
        # Adiciona o valor ao saldo atual
        self.saldo += valor

    def sacar(self, valor):
        # Método para sacar um valor da conta
        # Verifica se há saldo suficiente antes de realizar o saque
        if self.saldo >= valor:
            self.saldo -= valor
            print(
                f"Saque de R$ {valor:.2f} realizado com sucesso. "
                f"Novo saldo: R$ {self.saldo:.2f}"
            )
        else:
            print(
                f"Erro: Saldo insuficiente. "
                f"Seu saldo atual é R$ {self.saldo:.2f}"
            )


# Exemplo de uso da classe Conta

# 1. Criação de uma instância da classe Conta
conta_maria = Conta("Maria Oliveira", 1500.00)

# 2. Impressão do saldo antes do depósito
print(f"Saldo antes do depósito: R$ {conta_maria.saldo:.2f}")

# 3. Realização de um depósito
valor_deposito = 300.00
conta_maria.depositar(valor_deposito)

# 4. Impressão do saldo depois do depósito
print(f"Saldo após o depósito de R$ {valor_deposito:.2f}: R$ {conta_maria.saldo:.2f}")

Conta criada para Maria Oliveira com saldo inicial de R$ 1500.00.
Saldo antes do depósito: R$ 1500.00
Saldo após o depósito de R$ 300.00: R$ 1800.00

In [38]:
# Reutilizando a definição da classe Conta do bloco anterior
# (Assumimos que a classe Conta já está definida e executada no ambiente)

# Exemplo de uso da classe Conta com operações de saque

# 1. Criação de uma nova instância da classe Conta para demonstração de saques
print("\n--- Demonstrando operações de Saque ---")
conta_joao = Conta("João Silva", 2000.00)

# 2. Saque dentro do saldo disponível
print(f"Saldo antes do primeiro saque: R$ {conta_joao.saldo:.2f}")
valor_saque_1 = 500.00
print(f"Tentando sacar: R$ {valor_saque_1:.2f}")
conta_joao.sacar(valor_saque_1)
print(f"Saldo após o primeiro saque: R$ {conta_joao.saldo:.2f}")

# 3. Saque além do saldo remanescente
print(f"\nSaldo antes do segundo saque: R$ {conta_joao.saldo:.2f}")
valor_saque_2 = 1800.00 # Este valor é maior que o saldo restante (2000 - 500 = 1500)
print(f"Tentando sacar: R$ {valor_saque_2:.2f}")
conta_joao.sacar(valor_saque_2)
print(f"Saldo final: R$ {conta_joao.saldo:.2f}")

--- Demonstrando operações de Saque ---
Conta criada para João Silva com saldo inicial de R$ 2000.00.
Saldo antes do primeiro saque: R$ 2000.00
Tentando sacar: R$ 500.00
Saque de R$ 500.00 realizado com sucesso. Novo saldo: R$ 1500.00
Saldo após o primeiro saque: R$ 1500.00

Saldo antes do segundo saque: R$ 1500.00
Tentando sacar: R$ 1800.00
Erro: Saldo insuficiente. Seu saldo atual é R$ 1500.00
Saldo final: R$ 1500.00

## Método __str__

Cria classe.

In [45]:
# Definição da classe Conta para representar uma conta bancária
class Conta:
    def __init__(self, titular, saldo):
        # Construtor da classe Conta
        # Inicializa a conta com um titular e um saldo inicial
        self.titular = titular
        self.saldo = saldo
        print(f"Conta criada para {self.titular} com saldo inicial de R$ {self.saldo:.2f}.")

    def __str__(self) -> str:
        return f"Cliente: {self.titular} | Saldo: R$ {self.saldo:.2f}"

    def depositar(self, valor):
        # Método para depositar um valor na conta
        # Adiciona o valor ao saldo atual
        self.saldo += valor

    def sacar(self, valor):
        # Método para sacar um valor da conta
        # Verifica se há saldo suficiente antes de realizar o saque
        if self.saldo >= valor:
            self.saldo -= valor
            print(
                f"Saque de R$ {valor:.2f} realizado com sucesso. "
                f"Novo saldo: R$ {self.saldo:.2f}"
            )
        else:
            print(
                f"Erro: Saldo insuficiente. "
                f"Seu saldo atual é R$ {self.saldo:.2f}"
            )

Cria conta [objeto].

In [46]:
conta_pedro = Conta("Pedro Soares", 30000)

print(conta_pedro)

Conta criada para Pedro Soares com saldo inicial de R$ 30000.00.
Cliente: Pedro Soares | Saldo: R$ 30000.00

# Bibliotecas/módulos

In [48]:
import openpyxl

import pandas as pd

## Pandas

In [58]:
df = pd.DataFrame(clientes)
df.head()

clientes_aprovados = df[df["score_credito"] >= 600]

# Ordenar os clientes aprovados por 'score_credito' em modo decrescente
clientes_aprovados = clientes_aprovados.sort_values('score_credito', ascending=False)

# Exibir os clientes aprovados
print("Clientes Aprovados:")

print("Total de aprovados:", len(clientes_aprovados))
clientes_aprovados

Clientes Aprovados:
Total de aprovados: 14

               cpf      nome  sobrenome     renda  score_credito
18  705.964.023-17      João  Gonçalves  13147.98            876
1   074.391.500-31    Otavio      Rocha   2330.80            854
19  634.168.587-43   Eduarda    Martins  11983.37            845
11  341.925.412-11       Ana      Costa   4075.13            840
16  208.093.972-69    Ursula      Costa  12762.87            821
8   288.360.759-16   Natalia  Gonçalves   9207.22            816
10  892.184.011-73  Henrique    Pereira  13285.02            763
3   068.124.158-63  Patricia  Rodrigues  14173.73            732
15  423.041.144-82    Otavio     Santos  11669.95            726
4   449.786.907-57   Sabrina   Ferreira   5155.62            713
17  351.396.937-63     Bruno    Ribeiro   3357.51            699
0   141.777.631-52   Eduarda      Nunes   8342.14            699
5   585.178.128-91    Otavio    Pereira  12919.37            679
14  683.873.806-60  Patricia  Gonçalves  10773.73            628

In [74]:
clientes_qualificados = df[
    (df["renda"] > 4000) &
    (df["score_credito"] > 700)
]
clientes_qualificados = clientes_qualificados.sort_values("score_credito", ascending=False)

print("Clientes com renda > 4000 e score_credito > 700:")
clientes_qualificados

Clientes com renda > 4000 e score_credito > 700:

               cpf      nome  sobrenome     renda  score_credito
18  705.964.023-17      João  Gonçalves  13147.98            876
19  634.168.587-43   Eduarda    Martins  11983.37            845
11  341.925.412-11       Ana      Costa   4075.13            840
16  208.093.972-69    Ursula      Costa  12762.87            821
8   288.360.759-16   Natalia  Gonçalves   9207.22            816
10  892.184.011-73  Henrique    Pereira  13285.02            763
3   068.124.158-63  Patricia  Rodrigues  14173.73            732
15  423.041.144-82    Otavio     Santos  11669.95            726
4   449.786.907-57   Sabrina   Ferreira   5155.62            713

## openpyxl

In [77]:
caminho = "clientes.xlsx"
df.to_excel(caminho, index=False)